### ISSUE TITLE
Map Icons dont work

### ISSUE THREAD

**Issue by Larry-Lizard** [kurt-stolle/mapvote#2]
I´ve put the Map icons into materials/excl_mapvote/maps folder and they dont load in. They have the correct size and the correct format. They also have the same name as the map.

**Comment by Larry-Lizard** [comment]
Closing the Issue, rewrote the Code to make it work.

**Comment by khwstolle** [comment]
If you have made edits that work for your specific setup, please make a pull request so that people with a setup similar to yours can enjoy it too.
